"""
Hardware Simulator - Sends real-time sensor data to backend
============================================================
This script simulates an ESP32/Arduino device by sending realistic
sensor data to the Django backend every 100ms (just like real hardware).

Use this to test real-time readings WITHOUT physical hardware!

Requirements:
- Backend server running on http://127.0.0.1:8000
- Device token from database (generated by seed_data.py)

Usage:
python hardware_simulator.py
"""

import requests
import time
import random
import math
from datetime import datetime

# ─────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────
SERVER_URL = "http://127.0.0.1:8000/api/v1"
DEVICE_TOKEN = ""  # Will be auto-filled from database if empty

# Simulation settings
SEND_INTERVAL_SEC = 0.1  # 100ms (same as Arduino firmware)
SIMULATE_GESTURES = True  # Simulate different gestures automatically

# Gesture patterns (EMG value ranges)
GESTURE_PATTERNS = {
    'IDLE':   {'emg_base': 40, 'emg_var': 20, 'force': 0.1},
    'OPEN':   {'emg_base': 200, 'emg_var': 50, 'force': 0.2},
    'GRIP':   {'emg_base': 650, 'emg_var': 100, 'force': 5.5},
    'PINCH':  {'emg_base': 380, 'emg_var': 60, 'force': 2.5},
    'ROTATE': {'emg_base': 150, 'emg_var': 40, 'force': 1.0},
}


def get_device_token():
    """Auto-fetch device token from database for 'patient1' user."""
    try:
        import os
        import django
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'bionic_backend.settings')
        django.setup()
        
        from core.models import DeviceToken
        token_obj = DeviceToken.objects.get(user__username='patient1')
        print(f"✅ Using device token for patient1: {token.token[:16]}...")
        return token.token
    except Exception as e:
        print(f"⚠️  Could not fetch token from database: {e}")
        print("📝 Please enter your device token manually or run: python seed_data.py")
        return input("Enter device token: ").strip()


def generate_sensor_data(gesture='IDLE', t=None):
    """
    Generate realistic sensor data based on gesture type.
    
    Args:
        gesture: Type of gesture being simulated
        t: Time offset for wave patterns
    
    Returns:
        Dictionary with sensor values
    """
    pattern = GESTURE_PATTERNS.get(gesture, GESTURE_PATTERNS['IDLE'])
    
    # EMG with noise and occasional spikes
    emg_value = pattern['emg_base'] + random.uniform(-pattern['emg_var'], pattern['emg_var'])
    if t and SIMULATE_GESTURES:
        # Add sine wave modulation for dynamic effect
        emg_value += 30 * math.sin(t * 0.5)
    emg_value = max(0, min(1023, emg_value))  # Clamp to ADC range
    
    # Force sensor (0-10 Newtons)
    force_value = pattern['force'] + random.uniform(-0.3, 0.3)
    force_value = max(0, min(10, force_value))
    
    # IMU motion data (simulating MPU6050 accelerometer)
    # Values typically range from -1 to 1 (gravity normalized)
    motion_x = random.uniform(-0.2, 0.2) + (0.1 * math.sin(t * 0.3) if t else 0)
    motion_y = random.uniform(-0.2, 0.2) + (0.1 * math.cos(t * 0.3) if t else 0)
    motion_z = 0.98 + random.uniform(-0.05, 0.05)  # Gravity ~1.0
    
    # Battery level (slowly decreasing over time)
    battery_level = max(15, 100 - (time.time() % 3600) / 36)  # Drops over an hour
    
    return {
        'emg': round(emg_value, 2),
        'force': round(force_value, 2),
        'motion_x': round(motion_x, 3),
        'motion_y': round(motion_y, 3),
        'motion_z': round(motion_z, 3),
        'battery': int(battery_level),
    }


def send_sensor_data(data, token):
    """
    Send sensor data to backend hardware push endpoint.
    
    Args:
        data: Dictionary with sensor readings
        token: Device authentication token
    
    Returns:
        Response JSON from server or None on error
    """
    url = f"{SERVER_URL}/hardware/push/"
    headers = {
        'Content-Type': 'application/json',
        'X-Device-Token': token,
    }
    
    try:
        response = requests.post(url, json=data, headers=headers, timeout=2)
        
        if response.status_code == 200:
            return response.json()
        else:
            print(f"❌ HTTP Error {response.status_code}: {response.text}")
            return None
            
    except requests.exceptions.ConnectionError:
        print("❌ Connection error - Is backend running on http://127.0.0.1:8000?")
        return None
    except requests.exceptions.Timeout:
        print("❌ Request timeout")
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None


def simulate_gesture_cycle():
    """Cycle through different gestures to show variety in UI."""
    gestures = ['IDLE', 'OPEN', 'GRIP', 'PINCH', 'ROTATE']
    
    print("\n🎭 Starting gesture simulation cycle...")
    print("   Will cycle through: " + " → ".join(gestures))
    print("   Each gesture lasts ~3 seconds\n")
    
    return gestures


def main():
    """Main simulator loop."""
    print("=" * 60)
    print("🦾 AI Prosthetic Limb - Hardware Simulator")
    print("=" * 60)
    print("\n📡 This script simulates ESP32 hardware sending sensor data")
    print("   to the Django backend every 100ms.\n")
    
    # Get device token
    if not DEVICE_TOKEN:
        token = get_device_token()
    else:
        token = DEVICE_TOKEN
    
    print(f"\n🔑 Device Token: {token[:32]}...")
    print(f"🌐 Server URL: {SERVER_URL}")
    print(f"⏱️  Send Interval: {SEND_INTERVAL_SEC}s ({1/SEND_INTERVAL_SEC:.0f} Hz)\n")
    
    # Check backend connectivity
    print("🔍 Testing backend connection...")
    test_data = generate_sensor_data('IDLE')
    response = send_sensor_data(test_data, token)
    
    if response:
        print("✅ Backend connection successful!")
        print(f"   Initial command: {response.get('command', 'NONE')}")
        print(f"   AI Gesture: {response.get('gesture', 'Unknown')}")
        print(f"   Confidence: {response.get('confidence', 0):.1f}%\n")
    else:
        print("⚠️  Backend not responding. Please start Django server:")
        print("   cd bionic_backend")
        print("   python manage.py runserver\n")
        input("Press Enter to continue anyway...")
    
    # Start simulation
    print("=" * 60)
    print("🚀 Starting real-time data transmission...\n")
    
    start_time = time.time()
    packet_count = 0
    success_count = 0
    
    # Optional: Auto-cycle through gestures
    auto_gestures = simulate_gesture_cycle() if SIMULATE_GESTURES else None
    current_gesture_idx = 0
    last_gesture_change = start_time
    
    try:
        while True:
            current_time = time.time()
            elapsed = current_time - start_time
            
            # Change gesture every 3 seconds
            if auto_gestures and (current_time - last_gesture_change) > 3.0:
                current_gesture_idx = (current_gesture_idx + 1) % len(auto_gestures)
                gesture = auto_gestures[current_gesture_idx]
                last_gesture_change = current_time
                print(f"\n🎭 Gesture changed to: {gesture}")
            else:
                gesture = auto_gestures[current_gesture_idx] if auto_gestures else 'IDLE'
            
            # Generate and send data
            sensor_data = generate_sensor_data(gesture, elapsed)
            response = send_sensor_data(sensor_data, token)
            
            packet_count += 1
            if response:
                success_count += 1
                
                # Show status every 50 packets (every ~5 seconds)
                if packet_count % 50 == 0:
                    success_rate = (success_count / packet_count) * 100
                    print(f"\n📊 Stats: {packet_count} packets sent, "
                          f"{success_count} successful ({success_rate:.1f}%)")
                    print(f"   Latest: EMG={sensor_data['emg']:.1f}, "
                          f"Force={sensor_data['force']:.2f}N, "
                          f"Battery={sensor_data['battery']}%")
                    if response:
                        cmd = response.get('command', 'NONE')
                        ai = response.get('gesture', 'Unknown')
                        conf = response.get('confidence', 0)
                        print(f"   AI Prediction: {ai} ({conf:.1f}%)")
                        print(f"   Command: {cmd}")
            
            # Wait until next interval
            time.sleep(SEND_INTERVAL_SEC)
            
    except KeyboardInterrupt:
        print("\n\n⏹️  Simulator stopped by user")
        print(f"\n📊 Final Statistics:")
        print(f"   Total packets: {packet_count}")
        print(f"   Successful: {success_count}")
        print(f"   Success rate: {(success_count/packet_count)*100:.1f}%")
        print(f"   Duration: {elapsed:.1f} seconds")
        print(f"   Average rate: {packet_count/elapsed:.1f} packets/sec")


if __name__ == "__main__":
    main()
