# Generated by Django 6.0.3 on 2026-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='performance_metric',
            field=models.FloatField(default=0.0),
        ),
    ]
