# Generated by Django 6.0.3 on 2026-03-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemlog_emp_id_systemlog_performance_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='predicted_gesture',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('GRIP', 'Close Hand (Grip)'), ('RELEASE', 'Open Hand (Release)'), ('ROTATE_CW', 'Wrist Rotate Clockwise'), ('ROTATE_CCW', 'Wrist Rotate Counter-Clockwise'), ('PINCH', 'Precision Pinch'), ('STOP', 'Emergency Stop'), ('SLEEP', 'Sleep Mode'), ('CALIBRATE', 'Calibrate Sensors')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered to Hardware'), ('executed', 'Executed by Hardware')], default='pending', max_length=20)),
                ('issued_by', models.CharField(default='web', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(default='Prosthetic Limb v1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
